# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RobertHarrison.ca
email: harrisonrw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  San Diego based software developer specializing in iOS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robertharrison.ca"
twitter_username: robwh99
github_username:  harrisonrw

# Build settings
markdown: kramdown

kramdown:
  input: GFM

# Google Services
google_analytics: UA-40538920-1
